config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  post 'stringify', to: 'pages#stringify'

  put 'age', to: 'pages#person'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/foobar.rb
class Foobar

	def self.baz(input)
		input.map! { |i| i.to_i + 2}
		input.map! { |i| i if i.even? }
		input.uniq!
		input.select! {|x| !x.nil? }
		input.select! {|x| x < 10}
		return input.inject(:+)
	end
end

app/controllers/concerns/person.rb
class Person

	def initialize(name, age)
		@name = name
		@age = age
		@nickname = name[0, 4]
	end

	def introduce()
		"Hello, my name is #{@name}, and I am #{@age} years old."
	end

	def age()
		return @age
	end

	def birth_year()
		@birth_year = 2015 - @age.to_i
	end

	def nickname() 
		@nickname
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @baz = Foobar.baz ["1", "2", "3", "3", "4", "5", "10", "11", "100"]
  end

  def stringify
    @your_name = params[:name]
    @your_adjective = params[:adjective]
  end

  def age

  end

  def person
    @person1 = Person.new(params[:name], params[:age])
    # person1.initialize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/age.html.erb
<h1>REROUTE ME!</h1>

app/views/pages/home.html.erb
<h1>Hello There! Welcome to homework 2!</h1>
<p>What a beautiful homepage!</p>
<p>Good thing this isn't the web design decal.</p>

<h1>Question 1</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag stringify_path do %>
  <%= label_tag :name, "Your Name here!" %>
  <%= text_area_tag :name %>
  <%= label_tag :adjective, "An adjective here!" %>
  <%= text_area_tag :adjective %>
  <%= submit_tag "Stringify!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

<h1>Question 2</h1>

<p>Your result</p>
<%= @baz %>

<h1>Question 3</h1>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

<%= form_tag age_path, method: :put do %>
  <%= label_tag :name, "Your name:" %>
  <%= text_area_tag :name %>
  <%= label_tag :age, "Your age:" %>
  <%= text_area_tag :age %>
  <%= submit_tag "Submit!" %>
<% end %>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

app/views/pages/person.html.erb
<h1><%= @person1.introduce %></h1>
<h2><%= @person1.birth_year %> is your age</h2>
<h3><%= @person1.nickname %> is your nickname</h3>

app/views/pages/stringify.html.erb
<h1>Hello</h1>

<% if @your_name.blank? %>
	<h1> You are nothing!</h1>
<% else %>
	<h1><%= @your_name %> is <%= @your_adjective %></h1>
<% end %> 